services:
  app:
    build:
      context: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/cripto
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Ajout de la configuration Hibernate pour la mise à jour du schéma
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cripto
    volumes:
      - mysql-data:/var/lib/mysql  # Ajout du volume pour persister les données
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:  # Déclaration du volume
