spring.datasource.url=jdbc:mysql://mysql-container:3306/cripto
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update  # Option pour permettre à Hibernate de mettre à jour le schéma
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=girlspower434@gmail.com
spring.mail.password=sjguswuxjdhbghld
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
